# Generated by Django 3.0.2 on 2020-02-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('address', models.TextField(max_length='1024', verbose_name='Адрес доставки')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный номер телефона')),
                ('comment', models.TextField(max_length='1024', verbose_name='Комментарий')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store_app.Customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_per_item', models.PositiveIntegerField(verbose_name='Цена за шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store_app.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store_app.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'заказанный продукт',
                'verbose_name_plural': 'заказанные продукты',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store_app.Customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store_app.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'продукт корзины',
                'verbose_name_plural': 'продукты корзины',
            },
        ),
    ]
