# Generated by Django 3.0.2 on 2020-02-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('display_order', models.PositiveSmallIntegerField(help_text='Чем меньше значение, тем выше в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='SellingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, verbose_name='Параметр')),
                ('value', models.PositiveIntegerField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'параметр',
                'verbose_name_plural': 'параметры',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza_store_app.Category', verbose_name='Категория продукта'),
        ),
    ]
