# Generated by Django 3.0.2 on 2020-02-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store_app', '0002_auto_20200202_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], default='USD', max_length=3, verbose_name='Валюта')),
                ('rate_to_dollar', models.FloatField(verbose_name='Курс к доллару')),
                ('symbol', models.CharField(max_length=1, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pizza_store_app.Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
