# Generated by Django 3.0.2 on 2020-02-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store_app', '0003_auto_20200205_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='test address', max_length=1024, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена в евро'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
