# Generated by Django 3.0.2 on 2020-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store_app', '0006_auto_20200207_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=512, verbose_name='Файл с изображением'),
        ),
    ]
